### ISSUE TITLE
Solution for <Link>

### ISSUE THREAD

**Issue by NotDemonix** [NourAlzway/use-router-with-events#1]
So if I make a custom Link component with the onClick solution. Is prefetch still supported?

**Comment by NourAlzway** [comment]
Hi @NotDemonix, great question!

Yes, prefetch is still supported when using a custom `Link` component with `onClick` and `use-router-with-events`. 

The pacakge doesn’t interfere with the prefetch functionality of Next.js’s `Link` component. You can continue using `prefetch` as usual

Just make sure to pass the `prefetch` prop to Next.js's `Link` component to enable prefetching as usual. This way, you can have both prefetching and custom navigation logic seamlessly.

Thanks for the great question! Closing this issue now, but feel free to reach out if you have more questions.
